//
//  MapGenerator.swift
//  Minnion Maze
//
//  Created by Timothy Barnard on 16/12/2014.
//  Copyright (c) 2014 Timothy Barnard. All rights reserved.
//

var map1 = ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "xooooooooooooooooooooooooooooxxx",
            "xoooboooooooooooooooooooooboooox",
            "xoooooooooooxxxoxxoooxooooooooox",
            "xoooooooooooxoooboooooooooboooxx",
            "xoooooxxxxxxboooooooooooooooooox",
            "xoobooooooooxooooooooxooooooooox",
            "xooxoooooooxoooooooooxooooooooxx",
            "xoooooxooooxxxxxxxxxxooooxxxxoxx",
            "xoobooxoooooooooooooxoooooooooox",
            "xxooooxooooooowwooooxoooooooooox",
            "xxxxxxxooooooowwooooxoxxxxooboox",
            "xxxxxxxxxxxxxxxxxxxxooooooooooox",
            "xoooooobooooooooooxoooooooooooox",
            "xooxooooooooooxooooxxxxoooooooxx",
            "xobxooxxxooooooxooooooxoooooooox",
            "xooooooooooooxoxooooooxxxxxoboox",
            "xxxxxxxxxxxooxoxxxooooxoooooooox",
            "xooooobooooboxooooooooooobooooox",
            "xoboxxxoooxxxxoooooxxoooooooooox",
            "xoooxoooboooooooooooooooooooooox",
            "xoooxoooooobooooooooooooboooooox",
            "xoooxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]

var map2 = ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "xooooooooooooooooooooooooooooxxx",
            "xoooboooooooooooooooooooooboooox",
            "xoooooooooooxxxoxxoooxooooooooox",
            "xoooooooooooxoooboooooooooboooxx",
            "xoooooxxxxxxboooooooooooooooooox",
            "xoobooooooooxooooooooxooooooooox",
            "xooxoooooooxoooooooooxooooooooxx",
            "xoooooxooooxxxxxxxxxxooooxxxxoxx",
            "xoobooxoooooooooooooxoooooooooox",
            "xxooooxooooooowwooooxoooooooooox",
            "xxxxxxxooooooowwooooxoxxxxooboox",
            "xxxxxxxxxxxxxxxxxxxxooooooooooox",
            "xoooooobooooooooooxoooooooooooox",
            "xooxooooooooooxooooxxxxoooooooxx",
            "xobxooxxxooooooxooooooxoooooooox",
            "xooooooooooooxoxooooooxxxxxoboox",
            "xxxxxxxxxxxooxoxxxooooxoooooooox",
            "xooooobooooboxooooooooooobooooox",
            "xoboxxxoooxxxxoooooxxoooooooooox",
            "xoooxoooboooooooooooooooooooooox",
            "xoooxoooooobooooooooooooboooooox",
            "xooooooooooooxxxxxxxxxxxxxxxxxxx"]


var map3 = ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "xooooooooooooooooooooooooooooxxx",
            "xoooboooooooooooooooooooooboooox",
            "xoooooooooooxxxoxxoooxooooooooox",
            "xoooooooooooxoooboooooooooboooxx",
            "xoooooxxxxxxboooooooooooooooooox",
            "xoobooooooooxooooooooxooooooooox",
            "xooxoooooooxoooooooooxooooooooxx",
            "xoooooxooooxxxxxxxxxxooooxxxxoxx",
            "xoobooxoooooooooooooxoooooooooox",
            "xxooooxooooooowwooooxoooooooooox",
            "xxxxxxxooooooowwooooxoxxxxooboox",
            "xxxxxxxxxxxxxxxxxxxxooooooooooox",
            "xoooooobooooooooooxoooooooooooox",
            "xooxooooooooooxooooxxxxoooooooxx",
            "xobxooxxxooooooxooooooxoooooooox",
            "xooooooooooooxoxooooooxxxxxoboox",
            "xxxxxxxxxxxooxoxxxooooxoooooooox",
            "xooooobooooboxooooooooooobooooox",
            "xoboxxxoooxxxxoooooxxoooooooooox",
            "xoooxoooboooooooooooooooooooooox",
            "xoooxoooooobooooooooooooboooooox",
            "xooooooooooooxxxxxxxxxxxxxxxxxxx"]


var map4 = ["xxxoooxxxxwwwxxxxxxxxxxxxxxxxxxx",
            "xxxxxxxxxxooooxxxxxboooooobxxxxx",
            "xxxxboooooooooxxxxxxxxoxxxxxxxxx",
            "xxxxoxxxxoxxxxxooooooooooxxxxxxx",
            "xxxxoxxxxxxxxxxoxxxxxxxoxxxxxxxx",
            "xxxxbxxxxbooooooxxxxxoboxxxxxxxx",
            "xxxxoooooooboooxxxxooooooxxxxxxx",
            "xxxxxxxxxxxxoxxxxxxxxxxoxxxxxxxx",
            "xxxxxbooooooooobooooooooxxxxxxxx",
            "xxxxxoxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "xxxxxoxxxxxxobooxxxxxxxxxxxxxxxx",
            "xxxxxoooooboxxxxxxxxxxxxxxxxxxxx",
            "xxxxxxxxxooooxxxxxxxxoxxxxxxxxxx",
            "xxxxxxxxxxxxoooooooooboxxxxxxxxxx",
            "xxxxxxxoxxxxxxxxxxxxxoxxxxxxxxxx",
            "xxxxxxxoxxxxooooooooooxxxxxxxxxx",
            "xoooobooxxxxxxoxxxxxoxxxxxxxxxxx",
            "xoxxxxxooooooboxxxxxoooxxxxxxxxx",
            "xoxxxxxxxxoxxxxxxxxxoboxxxxxxxxx",
            "xooxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]


